# Google OAuth2 credentials
# Fill in your actual Google Cloud Console credentials
GOOGLE_CLIENT_ID=86477435563-6taa6pvv9v4n5usbq4925d33ejjnl8k3.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
